import com.xpdustry.toxopid.spec.ModMetadata
import com.xpdustry.toxopid.spec.ModPlatform

plugins {
  id "java"
  id "com.xpdustry.toxopid" version "4.2.0"
  id "net.kyori.indra.publishing" version "4.0.0"
}

def metadata = ModMetadata.fromJson(file("mod.hjson"))
group = "fr.zetamap"
version = metadata.version
description = metadata.description

repositories {
  mavenCentral()
  maven { url "https://maven.xpdustry.com/mindustry" }
  maven { url "https://www.jitpack.io" }
}

toxopid {
  compileVersion = "v${metadata.minGameVersion}"
  platforms = [ModPlatform.DESKTOP]
}

compileJava {
  targetCompatibility = JavaVersion.VERSION_17
  sourceCompatibility = JavaVersion.VERSION_17
  options.encoding = "UTF-8"
  options.release = 17
}

dependencies {
  compileOnly toxopid.dependencies.mindustryCore
}

processResources.from(rootDir) {
  include "mod.hjson"
}

jar {
  archiveFileName = "${metadata.name}.jar"

  //copy the builded jar to the working directory
  doLast {
    copy {
      from jar
      into rootDir
    }
  }
}

// Publishing
signing {
  def signingKey = findProperty("signingKey")
  def signingPassword = findProperty("signingPassword")
  useInMemoryPgpKeys(signingKey, signingPassword)
}

indra {
  javaVersions {
    target(17)
    minimumToolchain(17)
  }
    
  mitLicense()
  publishReleasesTo("xpdustry", "https://maven.xpdustry.com/zetamap")

  def repo = metadata.repository.split("/")
  github(repo[0], repo[1]) {
    ci(true)
    issues(true)
    scm(true)
  }

  configurePublications {
    // Why isn't it already included?
    from components.java
    artifact sourcesJar
    artifact javadocJar
  
    pom.developers {
	  metadata.author.split(",").each { a ->
	    developer {
	      id = a.trim()
	      url = "https://github.com/${id.get()}"
	    }
	  }
    }
  }
}

// I want these to only be included when publishing, not all the time...
task javadocJar(type: Jar, dependsOn: 'javadoc') {
  from javadoc.destinationDir
  javadoc.options.addStringOption('Xdoclint:none', '-quiet')
  archiveClassifier = 'javadoc'
}
task sourcesJar(type: Jar, dependsOn: 'classes') {
  from sourceSets.main.allSource
  archiveClassifier = 'sources'
}
